[tool.ruff]

# Exclude this file itself
exclude = ["ruff.toml"]

# What rules to enable
select = [
    "E",
    "W",
    "N",
]

[naming]
class-case = "PascalCase"
function-case = "camelCase"
variable-case = "camelCase"
constant-case = "UPPER_CASE"
argument-case = "camelCase"
attribute-case = "camelCase"
